# Generated by Django 3.1.2 on 2021-01-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='rep_code',
            new_name='Emp_code',
        ),
    ]
